name: Katariina Agnes Fagering
favicon: null
layout_spectrum: 0.1509
typography_spectrum: 0.5238790791481733
title: Katariina Agnes Fagering
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#fefee2'
    - '#cab394'
    - '#223458'
    - '#878883'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
