name: Katariina Agnes Fagering
favicon: null
layout_spectrum: 0.1509
typography_spectrum: 0.5238790791481733
title: Katariina Agnes Fagering
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1019'
    - '#d7dbde'
    - '#5d2c24'
    - '#bc7654'
    - '#67786b'
  brandStrength: 0.5625
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
